# Generated by Django 5.0.3 on 2024-03-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('ph_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('stud_class', models.CharField(max_length=50)),
                ('stud_year', models.IntegerField()),
            ],
        ),
    ]
