# Generated by Django 5.0.3 on 2024-03-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
