# Generated by Django 5.0.3 on 2024-03-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_table', '0003_remove_student_id_alter_student_reg_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_qualification', models.CharField(max_length=100)),
                ('teacher_degrees', models.TextField()),
                ('teacher_speciality', models.CharField(max_length=100)),
                ('teacher_certificate', models.CharField(max_length=100)),
                ('teacher_class_issued', models.CharField(max_length=100)),
                ('teacher_subjects', models.TextField()),
                ('teacher_contact', models.CharField(max_length=20)),
                ('teacher_email', models.EmailField(max_length=100)),
                ('teacher_post', models.CharField(max_length=100)),
            ],
        ),
    ]
