# Generated by Django 5.0.3 on 2024-03-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_table', '0004_faculty'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faculty',
            table='faculty',
        ),
    ]
