# Generated by Django 5.0.3 on 2024-03-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_table', '0005_alter_faculty_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='faculty',
            new_name='faculties',
        ),
    ]
