# Generated by Django 5.0.3 on 2024-03-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_table', '0006_rename_faculty_faculties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculties',
            name='id',
        ),
        migrations.AlterField(
            model_name='faculties',
            name='teacher_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
