# Generated by Django 5.0.3 on 2024-03-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_table', '0008_library_alter_student_address_alter_student_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_books', models.TextField()),
                ('course_subject', models.CharField(max_length=100)),
                ('course_year', models.IntegerField()),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
