# Generated by Django 5.0.3 on 2024-04-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_table', '0013_alter_course_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_year',
            field=models.DateField(),
        ),
    ]
