# Generated by Django 5.0.3 on 2024-04-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_table', '0018_uploadedfile_delete_dynamicdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
