# Generated by Django 5.0.3 on 2024-04-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_alter_photo_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='category',
        ),
    ]
