# Generated by Django 5.0.3 on 2024-05-01 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_rename_categories_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='category',
            new_name='Category',
        ),
    ]
