# Generated by Django 5.0.3 on 2024-05-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_rename_category_photo_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Category',
            new_name='category',
        ),
    ]
