# Generated by Django 5.0.3 on 2024-05-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
