# Generated by Django 5.0.3 on 2024-05-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0008_alter_uploadedfile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
